### PR TITLE
test: use archunit to ensure lazy fetch and private getters

### PR DESCRIPTION
**Pull request by anugrahsinghal**
adds an archunit test that takes care of verifying that
the associations are marked with lazy fetch type
and those fields have a private getter to ensure
no access from outside

Refs: #29

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
hey @anugrahsinghal can you please make sure that the run tests PR check passes?

**Comment by anugrahsinghal** [comment]
> hey @anugrahsinghal can you please make sure that the run tests PR check passes?

yeah, I ran the workflow on my repo.

What does the PR workflow look like now?

prev GH-Action used to run tests on the PR itself, now it checks if PR is run on the forked repo.

Any way to ensure that the fork always runs the tests?

**Comment by anugrahsinghal** [comment]
https://github.com/anugrahsinghal/supertokens-sql-plugin/runs/6384963655?check_suite_focus=true

ran the tests, how to sync with this PR?

**Comment by rishabhpoddar** [comment]
@anugrahsinghal you just have to click on the details button next to the check and then on thast page there will be a way to re-run failed jobs. (i have done this already)

**Pull request merged**
