### PR TITLE
feat: github workflows changes

### PR DESCRIPTION
**Pull request by anugrahsinghal**
This change packages and exports the test report from gradle
after running the test suite
and also updates the checkout action version

### CODE REVIEW

**Comment by anugrahsinghal** [comment]
@rishabhpoddar 

do you think this can be useful?

the rationale is that instead of scrolling through the test logs in Github action
a user can export and see the test reports

**Comment by rishabhpoddar** [comment]
@anugrahsinghal this does seem useful - but does it hide the logs from the action output? Cause sometimes scrolling through it is simple enough.

**Comment by anugrahsinghal** [comment]
nope, no changes to the existing flow.

Please see this 👇 (an example run with the workflow applied)
https://github.com/anugrahsinghal/supertokens-sql-plugin/actions/runs/2676947592

**Comment by rishabhpoddar** [comment]
@anugrahsinghal this looks great! Will merge it once you mark it ready for review and once all PR checks pass here

**Review by rishabhpoddar — APPROVED** [review]

**Pull request merged**
